name: Труба

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  intro:
    runs-on: ubuntu-latest
    steps:
    - name: Intro
      run: echo "Эту трубу я посвещаю своему другу девпопсеру, любителю клопов и змей"

  binary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bot -v cmd/main.go

    - name: Test
      run: go test -v ./...

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: go-binary
        path: bot

    - name: Upload dockerfile
      uses: actions/upload-artifact@v2
      with:
        name: Dockerfile
        path: Dockerfile
  
  docker:
    runs-on: ubuntu-latest
    needs: binary
    steps:
    - name: Download binary
      uses: actions/download-artifact@v2
      with:
        name: go-binary

    - name: Download dockerfile
      uses: actions/download-artifact@v2
      with:
        name: Dockerfile
    - name: cmod
      run: chmod +x bot
    - name: check files
      run: ls -la
    
    - name: Build and Push Docker
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: 32133789756/toxicbot
        registry: docker.io
        tags: latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}