name: Труба

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Intro
      run: echo "Эту трубу я посвещаю своему другу девпопсеру, любителю клопов и змей"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o bot -mod=vendor -v cmd/main.go

    - name: Test
      run: go test -mod=vendor -v ./...

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: go-binary
        path: bot
    
    - name: Build Docker
      run: docker build . --file Dockerfile --tag toxic-bot:$(date +%s)